name: Build wireguard-vanity-key

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag/branch/commit (или latest)'
        required: false
        default: 'latest'
      go-version:
        description: 'Go version (>=1.25 для этой программы)'
        required: false
        default: '1.25.1'
      target-os:
        description: 'Target OS (windows/linux/darwin)'
        required: false
        default: 'windows'
      target-arch:
        description: 'Target arch (amd64/arm64)'
        required: false
        default: 'amd64'
      output-name:
        description: 'Имя файла артефакта'
        required: false
        default: 'wireguard-vanity-key.exe'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: Clone repo
        run: |
          git clone --depth 1 https://github.com/AlexanderYastrebov/wireguard-vanity-key.git src
          cd src
          if [ "${{ inputs.version }}" != "latest" ]; then
            git fetch --depth=1 origin "${{ inputs.version }}" || true
            git checkout "${{ inputs.version }}" || git checkout "tags/${{ inputs.version }}" || true
          fi

      - name: Build
        working-directory: src
        env:
          GOOS: ${{ inputs.target-os }}
          GOARCH: ${{ inputs.target-arch }}
          CGO_ENABLED: 0
        run: |
          OUT="$GITHUB_WORKSPACE/${{ inputs.output-name }}"
          go build -trimpath -o "$OUT" .
          ls -la "$OUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.output-name }}
          path: ${{ inputs.output-name }}
